//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Script/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""Phone"",
            ""id"": ""39a5f490-36c7-4477-9053-ac76507e027a"",
            ""actions"": [
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""10278eda-03be-4fc7-b72f-94fa0616861e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ebd32e70-e62f-4898-8148-2418c6915421"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""HairStysel"",
            ""id"": ""57e32f28-e049-4792-9436-66f01b74501f"",
            ""actions"": [
                {
                    ""name"": ""Touchhair"",
                    ""type"": ""Button"",
                    ""id"": ""d0238fcb-0d02-46ca-b3f7-d7328001b7ac"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""23a042b1-fe9e-4841-8817-843a80584936"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touchhair"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Phone
        m_Phone = asset.FindActionMap("Phone", throwIfNotFound: true);
        m_Phone_Click = m_Phone.FindAction("Click", throwIfNotFound: true);
        // HairStysel
        m_HairStysel = asset.FindActionMap("HairStysel", throwIfNotFound: true);
        m_HairStysel_Touchhair = m_HairStysel.FindAction("Touchhair", throwIfNotFound: true);
    }

    ~@PlayerInput()
    {
        UnityEngine.Debug.Assert(!m_Phone.enabled, "This will cause a leak and performance issues, PlayerInput.Phone.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_HairStysel.enabled, "This will cause a leak and performance issues, PlayerInput.HairStysel.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Phone
    private readonly InputActionMap m_Phone;
    private List<IPhoneActions> m_PhoneActionsCallbackInterfaces = new List<IPhoneActions>();
    private readonly InputAction m_Phone_Click;
    public struct PhoneActions
    {
        private @PlayerInput m_Wrapper;
        public PhoneActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Click => m_Wrapper.m_Phone_Click;
        public InputActionMap Get() { return m_Wrapper.m_Phone; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PhoneActions set) { return set.Get(); }
        public void AddCallbacks(IPhoneActions instance)
        {
            if (instance == null || m_Wrapper.m_PhoneActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PhoneActionsCallbackInterfaces.Add(instance);
            @Click.started += instance.OnClick;
            @Click.performed += instance.OnClick;
            @Click.canceled += instance.OnClick;
        }

        private void UnregisterCallbacks(IPhoneActions instance)
        {
            @Click.started -= instance.OnClick;
            @Click.performed -= instance.OnClick;
            @Click.canceled -= instance.OnClick;
        }

        public void RemoveCallbacks(IPhoneActions instance)
        {
            if (m_Wrapper.m_PhoneActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPhoneActions instance)
        {
            foreach (var item in m_Wrapper.m_PhoneActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PhoneActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PhoneActions @Phone => new PhoneActions(this);

    // HairStysel
    private readonly InputActionMap m_HairStysel;
    private List<IHairStyselActions> m_HairStyselActionsCallbackInterfaces = new List<IHairStyselActions>();
    private readonly InputAction m_HairStysel_Touchhair;
    public struct HairStyselActions
    {
        private @PlayerInput m_Wrapper;
        public HairStyselActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Touchhair => m_Wrapper.m_HairStysel_Touchhair;
        public InputActionMap Get() { return m_Wrapper.m_HairStysel; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(HairStyselActions set) { return set.Get(); }
        public void AddCallbacks(IHairStyselActions instance)
        {
            if (instance == null || m_Wrapper.m_HairStyselActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_HairStyselActionsCallbackInterfaces.Add(instance);
            @Touchhair.started += instance.OnTouchhair;
            @Touchhair.performed += instance.OnTouchhair;
            @Touchhair.canceled += instance.OnTouchhair;
        }

        private void UnregisterCallbacks(IHairStyselActions instance)
        {
            @Touchhair.started -= instance.OnTouchhair;
            @Touchhair.performed -= instance.OnTouchhair;
            @Touchhair.canceled -= instance.OnTouchhair;
        }

        public void RemoveCallbacks(IHairStyselActions instance)
        {
            if (m_Wrapper.m_HairStyselActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IHairStyselActions instance)
        {
            foreach (var item in m_Wrapper.m_HairStyselActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_HairStyselActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public HairStyselActions @HairStysel => new HairStyselActions(this);
    public interface IPhoneActions
    {
        void OnClick(InputAction.CallbackContext context);
    }
    public interface IHairStyselActions
    {
        void OnTouchhair(InputAction.CallbackContext context);
    }
}
